double kiss(unsigned long *);
double gasdev(unsigned long *);
unsigned int runiform_n(unsigned int,unsigned long *);
unsigned long int runiform_long_n(unsigned long int,unsigned long *);
void permute_sample(double *,int,unsigned long *);
void permute_sample_int(int *,int,unsigned long *);
long rmultinomial(double *,long,unsigned long *);
long rmultinomialf(double *,long,unsigned long *);
double runif_atob(unsigned long *,double,double);
double rexp(double,unsigned long *);
double sgamma(double,unsigned long *);
double fsign(double,double);
double snorm(unsigned long *);
double snorm_tmp(unsigned long *);
double snorm2(unsigned long *);
double rnorm(double,double,unsigned long *);
double rgamma(double,double,unsigned long *);
double rinverse_gamma(double,double,unsigned long *);
double fact_ln(int);
int rpois(double,unsigned long *);
double *rdirichlet(double *,int,unsigned long *);
double *rdirichletf(double *,int,unsigned long *);
double rbeta(double,double,unsigned long *);
double rchisq(int , unsigned long * );